version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: VerySecurePassword
      MYSQL_DATABASE: application
    ports:
      - 3306:3306

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379