spring:
  application:
    name: BackendApplication
  datasource:
    url: jdbc:mariadb://localhost:3306/application
    username: root
    password: VerySecurePassword
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true

management:
  endpoint:
    health:
      show-components: always

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: com.example.backendapplication
  api-docs:
    path: /swagger

logging:
  level:
    org.springframework: INFO
    com.example.backendapplication: INFO

jwt:
  secretKey: secret
  issuer: www.example.com
  expirationMinute: 10

swagger:
  app-description: API Documentation for a simple task list application
  app-version: 1.0.0
  app-name: Task App